spring:
  application:
    name: BolgBackend
  datasource:
    url: jdbc:mysql://yunpin.cc:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: fgj
    password: fgj123
  data:
    redis:
      host: localhost
      port: 6379
      password:
      lettuce:
        pool:
          max-active: 8   # 连接池最大连接数
          max-idle: 8     # 连接池最大空闲连接数
          min-idle: 0     # 连接池最小空闲连接数
          max-wait: 100ms # 连接池最大等待时间
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:7b
  jackson:
    time-zone: Asia/Shanghai


logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    com.fingalden.bolg: debug

jwt:
  tokenSignKey: JamieBolg # 密钥
  tokenExpiration: 1 # 访问令牌过期时间（毫秒）