spring:
  application:
    name: BolgBackend
  datasource:
    url: jdbc:mysql://localhost:3306/bolg?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123465
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:7b

logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    com.fingalden.bolg: debug